# scripts/precommit/forbid_generated_edit.py
from __future__ import annotations

import sys
from pathlib import Path

REQUIRED_HEADER_FRAGMENT = "<auto-generated"


def main() -> int:
    failed = False

    for raw in sys.argv[1:]:
        path = Path(raw)

        if not path.exists() or path.suffix != ".cs":
            continue

        if not path.name.endswith(".g.cs"):
            continue

        text = path.read_text(encoding="utf-8", errors="ignore")
        head = text[:1000]

        if REQUIRED_HEADER_FRAGMENT not in head:
            print(f"[FAIL] Generated file missing auto-generated header: {path}")
            failed = True

    if failed:
        print()
        print("Generated files must include an <auto-generated /> header.")
        print("Do not manually edit generated files.")
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
